# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [3]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [34]:
#type your code here:
s = np.int_(5)
v = np.array([
    [5],
    [-2],
    [4]
])

A = np.array([
    [1 , 2 ,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [1,2,3],
    [4,5,6]
])

C = np.array([
    [1,2],
    [3,4],
    [5,6]
])

b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [35]:
#type your code here:
print(type(s))
print(type(v))
print(type(A))
print(type(B))
print(type(C))



<class 'numpy.int32'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [36]:
#type your code here:
print(s.shape)
print(v.shape)
print(A.shape)
print(B.shape)
print(C.shape)



()
(3, 1)
(3, 3)
(2, 3)
(3, 2)


d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [37]:
#type your code here:
print(A[2,1])

A = np.array([
    [1 , 2 ,3],
    [4,5,6],
    [7,10,9]
])
print(A)

8
[[1 2 3]
 [4 5 6]
 [7 8 9]]


e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

[[1, 2, 3], [4, 5, 6], [7, 10, 9]]

In [38]:
#type your code here:
print(A[:,[1]])
print(B[[1],:])


[[ 2]
 [ 5]
 [10]]
[[4 5 6]]


f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [39]:
#type your code here:
print(np.eye(4)), print(np.zeros(3)), print(np.zeros((3, 1))), print(np.zeros((3, 5)))
print(np.ones((2, 3))), print(np.diag([4, 5, 6, 7]))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0. 0. 0.]
[[0.]
 [0.]
 [0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


(None, None)

# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [40]:
#type your code here:
v1 = np.array([
    [1],
    [2],
    [7],
    [4]
])
v2 = np.array([
    [4],
    [3],
    [6],
    [8]
])
print(v1+v2)
print(v1-v2)
print(3*v1)
print(v1/2)

[[ 5]
 [ 5]
 [13]
 [12]]
[[-3]
 [-1]
 [ 1]
 [-4]]
[[ 3]
 [ 6]
 [21]
 [12]]
[[0.5]
 [1. ]
 [3.5]
 [2. ]]


b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [42]:
#type your code here:
print(np.dot(v1.T,v2))
print(np.matmul(v1.T,v2))
print(v1.T @ v2)

[[84]]
[[84]]
[[84]]


c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [43]:
#type your code here:
print(f"length of v1 using numpy.linalg.norm =\n{np.linalg.norm(v1)}\n")
print(f"length of v1 using numpy.linalg.norm =\n{np.linalg.norm(v2)}\n")
print(f"length of v1 Using the dot product and numpy.sqrt =\n{np.sqrt(v1.T @ v1)}\n")
print(f"length of v2 Using the dot product and numpy.sqrt =\n{np.sqrt(v2.T @ v2)}\n")

length of v1 using numpy.linalg.norm =
8.366600265340756

length of v1 using numpy.linalg.norm =
11.180339887498949

length of v1 Using the dot product and numpy.sqrt =
[[8.36660027]]

length of v2 Using the dot product and numpy.sqrt =
[[11.18033989]]



d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [44]:
#type your code here:
u = np.array([
    [3],
    [2],
    [-1],
    [4]
])
v= np.array([[1],[-1],[1],[0]])

print(f"u.T @ v = \n{u.T @ v}\n")

u.T @ v
[[0]]



# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [46]:
#type your code here:
u = np.array([[2],[7],[2]])
v = np.array([[8],[2],[4]])
A = np.array([
    [7,3,5],
    [4,6,2]
])
B = np.array([
    [0,6,4],
    [2,3,0]
])

print(A+B)
print("===================")
print(B+A)
print("===================")
print(3*A)
print("===================")
print(6*B)
print("===================")
print(2*(3*B))
print("===================")
print(6*A + 15*B)
print("===================")
print(3*(2*A + 5*B))
print("===================")
print((3*A.T).T)

[[7 9 9]
 [6 9 2]]
[[7 9 9]
 [6 9 2]]
[[21  9 15]
 [12 18  6]]
[[ 0 36 24]
 [12 18  0]]
[[ 0 36 24]
 [12 18  0]]
[[ 42 108  90]
 [ 54  81  12]]
[[ 42 108  90]
 [ 54  81  12]]
[[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [50]:
#type your code here:
print(f"Au + Av = \n{A @ u + A @ v }")
print(f"A(u + v) = \n{A @ (u+v)}")
print(f"(A + B) * u = \n{(A+B) @ v}")
print(f"Au + Bu = \n{A @ u + B @ u }")
print(f"A*(3u) = \n {A @ (3*u)}")
print(f"3A (u)\n {(3*A) @ u}")


Au + Av = 
[[127]
 [106]]
A(u + v) = 
[[127]
 [106]]
(A + B) * u = 
[[110]
 [ 74]]
Au + Bu = 
[[95]
 [79]]
A*(3u) = 
 [[135]
 [162]]
3A (u)
 [[135]
 [162]]


# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries 

In [51]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[9. 9. 3. 7.]
 [7. 3. 5. 5.]
 [9. 1. 0. 1.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix). 

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [56]:
#type your code here:
R = np.copy(A)

R[0,:] = R[0, :] / R[0, 0]

R[1, :] = R[1, :] - R[1, 0] * R[0, :]

R[2,:] = R[2,:] - R[2,0] * R[0,:]

print(R)

[[9. 9. 3. 7.]
 [7. 3. 5. 5.]
 [9. 1. 0. 1.]]
[[1.         1.         0.33333333 0.77777778]
 [7.         3.         5.         5.        ]
 [9.         1.         0.         1.        ]]
[[ 1.          1.          0.33333333  0.77777778]
 [ 0.         -4.          2.66666667 -0.44444444]
 [ 9.          1.          0.          1.        ]]
[[ 1.          1.          0.33333333  0.77777778]
 [ 0.         -4.          2.66666667 -0.44444444]
 [ 0.         -8.         -3.         -6.        ]]


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [59]:
#type your code here:
R[1,:] = R[1, :] / R[1, 1]

R[0,:] = R[0,:] - R[0,1] * R[1,:]

R[2,:] = R[2,:] - R[2,1] * R[1,:]

print(R)

[[ 1.          0.          1.          0.66666667]
 [-0.          1.         -0.66666667  0.11111111]
 [ 0.          0.         -8.33333333 -5.11111111]]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [61]:
#type your code here:
R[2,:] = R[2, :] / R[2, 2]

R[0,:] = R[0,:] - R[0,2] * R[2,:]

R[1,:] = R[1,:] - R[1,2] * R[2,:]

print(R)



[[ 1.          0.          0.          0.05333333]
 [-0.          1.          0.          0.52      ]
 [-0.         -0.          1.          0.61333333]]


#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [63]:
#type your code here:

# Use sympy.rref() method 
print(f"rank ={np.linalg.matrix_rank(R)}\n")
M = sym.Matrix(A)
M_rref = M.rref()
R = np.array((M_rref[0])).astype(np.float64)
print(M_rref)

rank =3

(Matrix([
[1, 0, 0, 0.0533333333333333],
[0, 1, 0,               0.52],
[0, 0, 1,  0.613333333333333]]), (0, 1, 2))


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$. 
 
2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [73]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    C = np.dot(A,B)
    

    ########################################################        
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(p):
        temp = A.dot(B[:,i])
        for j in range(m):
            C[j,i] = temp[j]

    ########################################################         
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    for i in range(m):
        temp = A[i,:].dot(B)
        for j in range(p):
            C[i,j] = temp[j]

    ########################################################         
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    temp1 = np.zeros((m,1))
    temp2 = np.zeros((n,1))
    C = 0
    for k in range(n):
        for x in range(n):
            temp2[x,0] = B[k,:][x]
        for y in range(m):
            temp1[y,0] = A[:,k][y]
        
        temp3 = temp1.dot(temp2.T)
        C += temp3


    ########################################################         
    return C

In [64]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

A = np.fix((10*(np.random.rand(300, 300))))
print(A)
B = np.fix((10*(np.random.rand(300, 300))))
print(B)

[[3. 5. 2. ... 0. 9. 8.]
 [5. 9. 0. ... 1. 5. 6.]
 [8. 0. 6. ... 3. 3. 9.]
 ...
 [5. 3. 2. ... 4. 7. 3.]
 [3. 8. 7. ... 0. 6. 2.]
 [2. 1. 6. ... 1. 6. 5.]]
[[5. 9. 8. ... 1. 5. 8.]
 [0. 4. 2. ... 5. 0. 8.]
 [8. 8. 0. ... 8. 5. 1.]
 ...
 [9. 1. 9. ... 0. 2. 2.]
 [5. 0. 6. ... 5. 4. 4.]
 [9. 7. 6. ... 3. 2. 1.]]


In [65]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[5794. 6237. 6016. ... 6639. 6226. 6026.]
 [5865. 6230. 6080. ... 6646. 6370. 6410.]
 [5737. 6051. 5613. ... 6375. 6280. 5843.]
 ...
 [5842. 6106. 6155. ... 6426. 6695. 6248.]
 [5617. 5838. 5629. ... 6318. 6270. 5830.]
 [5840. 5912. 5636. ... 6316. 6136. 5898.]]
Wall time: 452 ms


In [68]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[5794. 6237. 6016. ... 6639. 6226. 6026.]
 [5865. 6230. 6080. ... 6646. 6370. 6410.]
 [5737. 6051. 5613. ... 6375. 6280. 5843.]
 ...
 [5842. 6106. 6155. ... 6426. 6695. 6248.]
 [5617. 5838. 5629. ... 6318. 6270. 5830.]
 [5840. 5912. 5636. ... 6316. 6136. 5898.]]
Wall time: 8 ms


In [69]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[5794. 6237. 6016. ... 6639. 6226. 6026.]
 [5865. 6230. 6080. ... 6646. 6370. 6410.]
 [5737. 6051. 5613. ... 6375. 6280. 5843.]
 ...
 [5842. 6106. 6155. ... 6426. 6695. 6248.]
 [5617. 5838. 5629. ... 6318. 6270. 5830.]
 [5840. 5912. 5636. ... 6316. 6136. 5898.]]
Wall time: 104 ms


In [70]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[5794. 6237. 6016. ... 6639. 6226. 6026.]
 [5865. 6230. 6080. ... 6646. 6370. 6410.]
 [5737. 6051. 5613. ... 6375. 6280. 5843.]
 ...
 [5842. 6106. 6155. ... 6426. 6695. 6248.]
 [5617. 5838. 5629. ... 6318. 6270. 5830.]
 [5840. 5912. 5636. ... 6316. 6136. 5898.]]
Wall time: 171 ms


In [74]:
%%time
C_column_times_row = mat_mul_column_times_row(A, B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[5794. 6237. 6016. ... 6639. 6226. 6026.]
 [5865. 6230. 6080. ... 6646. 6370. 6410.]
 [5737. 6051. 5613. ... 6375. 6280. 5843.]
 ...
 [5842. 6106. 6155. ... 6426. 6695. 6248.]
 [5617. 5838. 5629. ... 6318. 6270. 5830.]
 [5840. 5912. 5636. ... 6316. 6136. 5898.]]
Wall time: 497 ms
